#!/usr/bin/env bash

INSTALL_DIR="./bin"
CIRCOM_BIN="$INSTALL_DIR/circom"

SRC_DIR="./src"
DST_DIR="./build"

mkdir -p "$DST_DIR"

POT=./pot20.ptau 

if [ ! -f $POT ]; then
  curl https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_20.ptau -o $POT
fi

echo "Compiling circuits"
for FILE in "$SRC_DIR"/joinsplit_*.circom; do 
  "$CIRCOM_BIN" --r1cs "$FILE" -o "$DST_DIR"
done

echo "Generating initial zkeys"
for FILE in "$DST_DIR"/*.r1cs; do 
  SEED="${FILE%.*}.00.zkey"

  npx snarkjs g16s "$FILE" "$POT" "$SEED"
done

rm "$BUILD_DIR"/*.0000

echo "Done!"
